# Form implementation generated from reading ui file 'designer.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1617, 1024)

        # entire application screen
        self.FRAME_main_window = QtWidgets.QFrame(Dialog)
        self.FRAME_main_window.setGeometry(QtCore.QRect(0, 0, 1491, 1001))
        self.FRAME_main_window.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.FRAME_main_window.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)

        #
        # MENU FRAME
        self.FRAME_main_window.setObjectName("FRAME_main_window")
        self.FRAME_menu = QtWidgets.QFrame(self.FRAME_main_window)
        self.FRAME_menu.setGeometry(QtCore.QRect(0, 0, 150, 500))
        self.FRAME_menu.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.FRAME_menu.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.FRAME_menu.setObjectName("FRAME_menu")
        # menu pane logo
        self.LABEL_logo = QtWidgets.QLabel(self.FRAME_menu)
        self.LABEL_logo.setGeometry(QtCore.QRect(0, 0, 150, 90))
        self.LABEL_logo.setObjectName("LABEL_logo")
        # "play" menu button
        self.PB_play = QtWidgets.QPushButton(self.FRAME_menu)
        self.PB_play.setGeometry(QtCore.QRect(0, 90, 150, 40))
        self.PB_play.setObjectName("PB_play")
        # "song gallery" menu button
        self.PB_song_gallery = QtWidgets.QPushButton(self.FRAME_menu)
        self.PB_song_gallery.setGeometry(QtCore.QRect(0, 130, 150, 40))
        self.PB_song_gallery.setText("")
        self.PB_song_gallery.setObjectName("PB_song_gallery")
        # "user guide" menu button
        self.PB_user_guide = QtWidgets.QPushButton(self.FRAME_menu)
        self.PB_user_guide.setGeometry(QtCore.QRect(0, 460, 150, 40))
        self.PB_user_guide.setObjectName("PB_user_guide")

        #
        # MAIN PLAY SCREEN
        self.FRAME_play = QtWidgets.QFrame(self.FRAME_main_window)
        self.FRAME_play.setGeometry(QtCore.QRect(150, 0, 601, 501))
        self.FRAME_play.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.FRAME_play.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.FRAME_play.setObjectName("FRAME_play")
        
        # mode selection frame (learning/testing)
        self.FRAME_mode = QtWidgets.QFrame(self.FRAME_play)
        self.FRAME_mode.setGeometry(QtCore.QRect(20, 20, 561, 80))
        self.FRAME_mode.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.FRAME_mode.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.FRAME_mode.setObjectName("FRAME_mode")
        self.LABEL_mode = QtWidgets.QLabel(self.FRAME_mode)
        self.LABEL_mode.setGeometry(QtCore.QRect(10, 10, 171, 61))
        self.LABEL_mode.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.LABEL_mode.setObjectName("LABEL_mode")
        self.PB_mode_1 = QtWidgets.QPushButton(self.FRAME_mode)
        self.PB_mode_1.setGeometry(QtCore.QRect(170, 20, 150, 40))
        self.PB_mode_1.setObjectName("PB_mode_1")
        self.PB_mode_2 = QtWidgets.QPushButton(self.FRAME_mode)
        self.PB_mode_2.setGeometry(QtCore.QRect(380, 10, 150, 40))
        self.PB_mode_2.setObjectName("PB_mode_2")

        # song selection frame
        self.FRAME_song = QtWidgets.QFrame(self.FRAME_play)
        self.FRAME_song.setGeometry(QtCore.QRect(20, 120, 561, 80))
        self.FRAME_song.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.FRAME_song.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.FRAME_song.setObjectName("FRAME_song")
        self.LABEL_song = QtWidgets.QLabel(self.FRAME_song)
        self.LABEL_song.setGeometry(QtCore.QRect(10, 10, 171, 61))
        self.LABEL_song.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.LABEL_song.setObjectName("LABEL_song")
        self.COMBO_song = QtWidgets.QComboBox(self.FRAME_song)
        self.COMBO_song.setGeometry(QtCore.QRect(170, 20, 341, 41))
        self.COMBO_song.setObjectName("COMBO_song")

        # tempo selection frame
        self.FRAME_tempo = QtWidgets.QFrame(self.FRAME_play)
        self.FRAME_tempo.setGeometry(QtCore.QRect(270, 60, 171, 61))
        self.FRAME_tempo.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.FRAME_tempo.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.FRAME_tempo.setObjectName("FRAME_tempo")
        self.SPIN_tempo = QtWidgets.QSpinBox(self.FRAME_tempo)
        self.SPIN_tempo.setGeometry(QtCore.QRect(170, 21, 61, 41))
        self.SPIN_tempo.setObjectName("SPIN_tempo")
        self.PB_tempo_1 = QtWidgets.QPushButton(self.FRAME_tempo)
        self.PB_tempo_1.setGeometry(QtCore.QRect(210, 370, 150, 40))
        self.PB_tempo_1.setObjectName("PB_tempo_1")
        self.PB_tempo_2 = QtWidgets.QPushButton(self.FRAME_tempo)
        self.PB_tempo_2.setGeometry(QtCore.QRect(210, 370, 150, 40))
        self.PB_tempo_2.setObjectName("PB_tempo_2")

        # final play button
        self.PB_play_2 = QtWidgets.QPushButton(self.FRAME_play)
        self.PB_play_2.setGeometry(QtCore.QRect(210, 370, 150, 40))
        self.PB_play_2.setObjectName("PB_play_2")

        # in-progress screen (to show while user is playing a song)
        self.FRAME_inProgress = QtWidgets.QFrame(self.FRAME_main_window)
        self.FRAME_inProgress.setGeometry(QtCore.QRect(150, 0, 601, 501))
        self.FRAME_inProgress.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.FRAME_inProgress.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.FRAME_inProgress.setObjectName("FRAME_inProgress")
        self.LABEL_inProgress = QtWidgets.QLabel(self.FRAME_inProgress)
        self.LABEL_inProgress.setGeometry(QtCore.QRect(10, 10, 171, 61))
        self.LABEL_inProgress.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.LABEL_inProgress.setObjectName("LABEL_inProgress")

        # input type frame (midi/microphone)
        self.FRAME_inputType = QtWidgets.QFrame(self.FRAME_play)
        self.FRAME_inputType.setGeometry(QtCore.QRect(20, 400, 561, 80))
        self.FRAME_inputType.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.FRAME_inputType.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.FRAME_inputType.setObjectName("FRAME_inputType")
        self.LABEL_inputType = QtWidgets.QLabel(self.FRAME_inputType)
        self.LABEL_inputType.setGeometry(QtCore.QRect(10, 10, 171, 61))
        self.LABEL_inputType.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.LABEL_inputType.setObjectName("LABEL_inputType")
        self.PB_inputType1 = QtWidgets.QPushButton(self.FRAME_inputType)
        self.PB_inputType1.setGeometry(QtCore.QRect(170, 20, 150, 40))
        self.PB_inputType1.setObjectName("PB_inputType1")
        self.PB_inputType2 = QtWidgets.QPushButton(self.FRAME_inputType)
        self.PB_inputType2.setGeometry(QtCore.QRect(380, 20, 150, 40))
        self.PB_inputType2.setObjectName("PB_inputType2")

        #
        # FEEDBACK SCREEN
        self.FRAME_feedback = QtWidgets.QFrame(self.FRAME_main_window)
        self.FRAME_feedback.setGeometry(QtCore.QRect(150, 0, 601, 501))
        self.FRAME_feedback.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.FRAME_feedback.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.FRAME_feedback.setObjectName("FRAME_feedback")
        self.LABEL_feedback1 = QtWidgets.QLabel(self.FRAME_feedback)
        self.LABEL_feedback1.setGeometry(QtCore.QRect(10, 10, 171, 61))
        self.LABEL_feedback1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.LABEL_feedback1.setObjectName("LABEL_feedback1")
        self.LABEL_feedback2 = QtWidgets.QLabel(self.FRAME_feedback)
        self.LABEL_feedback2.setGeometry(QtCore.QRect(10, 10, 171, 61))
        self.LABEL_feedback2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.LABEL_feedback2.setObjectName("LABEL_feedback2")
        self.LABEL_feedback3 = QtWidgets.QLabel(self.FRAME_feedback)
        self.LABEL_feedback3.setGeometry(QtCore.QRect(10, 10, 171, 61))
        self.LABEL_feedback3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.LABEL_feedback3.setObjectName("LABEL_feedback3")
        self.PB_feedback = QtWidgets.QPushButton(self.FRAME_feedback)
        self.PB_feedback.setGeometry(QtCore.QRect(210, 370, 150, 40))
        self.PB_feedback.setObjectName("PB_feedback")

        #
        # SONG GALLERY SCREEN
        self.FRAME_songGallery = QtWidgets.QFrame(self.FRAME_main_window)
        self.FRAME_songGallery.setGeometry(QtCore.QRect(150, 0, 601, 501))
        self.FRAME_songGallery.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.FRAME_songGallery.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.FRAME_songGallery.setObjectName("FRAME_songGallery")
        self.LABEL_songGallery = QtWidgets.QLabel(self.FRAME_songGallery)
        self.LABEL_songGallery.setGeometry(QtCore.QRect(10, 10, 171, 61))
        self.LABEL_songGallery.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.LABEL_songGallery.setObjectName("LABEL_songGallery")
        self.LIST_songGallery = QtWidgets.QListView(self.FRAME_songGallery)
        self.LIST_songGallery.setGeometry(QtCore.QRect(20, 40, 256, 192))
        self.LIST_songGallery.setObjectName("LIST_songGallery")
        self.PB_addSong = QtWidgets.QPushButton(self.FRAME_songGallery)
        self.PB_addSong.setGeometry(QtCore.QRect(210, 40, 150, 40))
        self.PB_addSong.setObjectName("PB_addSong")
        self.PB_removeSong = QtWidgets.QPushButton(self.FRAME_songGallery)
        self.PB_removeSong.setGeometry(QtCore.QRect(210, 150, 150, 40))
        self.PB_removeSong.setObjectName("PB_removeSong")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))

        # menu elements
        self.PB_play.setText(_translate("Dialog", "PLAY"))
        self.LABEL_logo.setText(_translate("Dialog", "TextLabel"))
        self.PB_user_guide.setText(_translate("Dialog", "USER GUIDE"))

        # mode selection elements
        self.LABEL_mode.setText(_translate("Dialog", "CHOOSE YOUR MODE"))
        self.PB_mode_1.setText(_translate("Dialog", "LEARNING"))
        self.PB_mode_2.setText(_translate("Dialog", "TESTING"))

        # song selection elements
        self.LABEL_song.setText(_translate("Dialog", "CHOOSE YOUR SONG"))
        
        # tempo selection elements
        self.SPIN_tempo.setSuffix(_translate("Dialog", "0"))
        self.PB_tempo_1.setText(_translate("Dialog", "PLAY WITHOUT TIMING"))
        self.PB_tempo_2.setText(_translate("Dialog", "PLAY WITH TIMING"))

        # final play button
        self.PB_play_2.setText(_translate("Dialog", "PLAY"))
        
        # in-progress label
        self.LABEL_inProgress.setText(_translate("Dialog", "SONG IN PROGRESS..."))

        # feedback elements
        self.LABEL_feedback1.setText(_translate("Dialog", "FEEDBACK"))
        self.LABEL_feedback2.setText(_translate("Dialog", "FEEDBACK"))
        self.LABEL_feedback3.setText(_translate("Dialog", "FEEDBACK"))
        self.PB_feedback.setText(_translate("Dialog", "RETURN TO PLAY SCREEN"))

        # input type elements
        self.LABEL_inputType.setText(_translate("Dialog", "CHOOSE INPUT TYPE"))
        self.PB_inputType1.setText(_translate("Dialog", "MIDI"))
        self.PB_inputType2.setText(_translate("Dialog", "MICROPHONE"))

        # song gallery elements
        self.LABEL_songGallery.setText(_translate("Dialog", "VIEW + EDIT YOUR SONG GALLERY"))
        self.PB_addSong.setText(_translate("Dialog", "ADD SONG"))
        self.PB_removeSong.setText(_translate("Dialog", "REMOVE SELECTED SONG"))