# Form implementation generated from reading ui file 'designer.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1617, 1024)

        # entire application screen
        self.FRAME_main_window = QtWidgets.QFrame(Dialog)
        self.FRAME_main_window.setGeometry(QtCore.QRect(0, 0, 1491, 1001))
        self.FRAME_main_window.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.FRAME_main_window.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)

        #
        # MENU FRAME
        self.FRAME_main_window.setObjectName("FRAME_main_window")
        self.FRAME_menu = QtWidgets.QFrame(self.FRAME_main_window)
        self.FRAME_menu.setGeometry(QtCore.QRect(0, 0, 150, 500))
        self.FRAME_menu.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.FRAME_menu.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.FRAME_menu.setObjectName("FRAME_menu")
        # menu pane logo
        self.LABEL_logo = QtWidgets.QLabel(self.FRAME_menu)
        self.LABEL_logo.setGeometry(QtCore.QRect(0, 0, 150, 90))
        self.LABEL_logo.setObjectName("LABEL_logo")
        # "play" menu button
        self.PB_play = QtWidgets.QPushButton(self.FRAME_menu)
        self.PB_play.setGeometry(QtCore.QRect(0, 90, 150, 40))
        self.PB_play.setObjectName("PB_play")
        # "song gallery" menu button
        self.PB_song_gallery = QtWidgets.QPushButton(self.FRAME_menu)
        self.PB_song_gallery.setGeometry(QtCore.QRect(0, 130, 150, 40))
        self.PB_song_gallery.setText("")
        self.PB_song_gallery.setObjectName("PB_song_gallery")
        # "user guide" menu button
        self.PB_user_guide = QtWidgets.QPushButton(self.FRAME_menu)
        self.PB_user_guide.setGeometry(QtCore.QRect(0, 460, 150, 40))
        self.PB_user_guide.setObjectName("PB_user_guide")

        #
        # MAIN PLAY SCREEN
        self.FRAME_play = QtWidgets.QFrame(self.FRAME_main_window)
        self.FRAME_play.setGeometry(QtCore.QRect(150, 0, 601, 501))
        self.FRAME_play.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.FRAME_play.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.FRAME_play.setObjectName("FRAME_play")
        
        # mode selection frame (learning/testing)
        self.FRAME_mode = QtWidgets.QFrame(self.FRAME_play)
        self.FRAME_mode.setGeometry(QtCore.QRect(20, 20, 561, 80))
        self.FRAME_mode.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.FRAME_mode.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.FRAME_mode.setObjectName("FRAME_mode")
        self.LABEL_mode = QtWidgets.QLabel(self.FRAME_mode)
        self.LABEL_mode.setGeometry(QtCore.QRect(10, 10, 171, 61))
        self.LABEL_mode.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.LABEL_mode.setObjectName("LABEL_mode")
        self.PB_mode_1 = QtWidgets.QPushButton(self.FRAME_mode)
        self.PB_mode_1.setGeometry(QtCore.QRect(170, 20, 150, 40))
        self.PB_mode_1.setObjectName("PB_mode_1")
        self.PB_mode_2 = QtWidgets.QPushButton(self.FRAME_mode)
        self.PB_mode_2.setGeometry(QtCore.QRect(380, 10, 150, 40))
        self.PB_mode_2.setObjectName("PB_mode_2")

        # song selection frame
        self.FRAME_song = QtWidgets.QFrame(self.FRAME_play)
        self.FRAME_song.setGeometry(QtCore.QRect(20, 120, 561, 80))
        self.FRAME_song.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.FRAME_song.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.FRAME_song.setObjectName("FRAME_song")
        self.LABEL_song = QtWidgets.QLabel(self.FRAME_song)
        self.LABEL_song.setGeometry(QtCore.QRect(10, 10, 171, 61))
        self.LABEL_song.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.LABEL_song.setObjectName("LABEL_song")
        self.COMBO_song = QtWidgets.QComboBox(self.FRAME_song)
        self.COMBO_song.setGeometry(QtCore.QRect(170, 20, 341, 41))
        self.COMBO_song.setObjectName("COMBO_song")

        # tempo selection frame
        self.FRAME_tempo = QtWidgets.QFrame(self.FRAME_play)
        self.FRAME_tempo.setGeometry(QtCore.QRect(270, 60, 171, 61))
        self.FRAME_tempo.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.FRAME_tempo.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.FRAME_tempo.setObjectName("FRAME_tempo")
        self.SPIN_tempo = QtWidgets.QSpinBox(self.FRAME_tempo)
        self.SPIN_tempo.setGeometry(QtCore.QRect(170, 21, 61, 41))
        self.SPIN_tempo.setObjectName("SPIN_tempo")
        self.PB_tempo_1 = QtWidgets.QPushButton(self.FRAME_tempo)
        self.PB_tempo_1.setGeometry(QtCore.QRect(210, 370, 150, 40))
        self.PB_tempo_1.setObjectName("PB_tempo_1")
        self.PB_tempo_2 = QtWidgets.QPushButton(self.FRAME_tempo)
        self.PB_tempo_2.setGeometry(QtCore.QRect(210, 370, 150, 40))
        self.PB_tempo_2.setObjectName("PB_tempo_2")

        # final play button
        self.PB_play_2 = QtWidgets.QPushButton(self.FRAME_play)
        self.PB_play_2.setGeometry(QtCore.QRect(210, 370, 150, 40))
        self.PB_play_2.setObjectName("PB_play_2")

        # in-progress screen (to show while user is playing a song)
        self.FRAME_inProgress = QtWidgets.QFrame(self.FRAME_main_window)
        self.FRAME_inProgress.setGeometry(QtCore.QRect(150, 0, 601, 501))
        self.FRAME_inProgress.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.FRAME_inProgress.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.FRAME_inProgress.setObjectName("FRAME_inProgress")
        self.LABEL_inProgress = QtWidgets.QLabel(self.FRAME_inProgress)
        self.LABEL_inProgress.setGeometry(QtCore.QRect(10, 10, 171, 61))
        self.LABEL_inProgress.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.LABEL_inProgress.setObjectName("LABEL_inProgress")

        # input type frame (midi/microphone)
        self.FRAME_inputType = QtWidgets.QFrame(self.FRAME_play)
        self.FRAME_inputType.setGeometry(QtCore.QRect(20, 400, 561, 80))
        self.FRAME_inputType.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.FRAME_inputType.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.FRAME_inputType.setObjectName("FRAME_inputType")
        self.LABEL_inputType = QtWidgets.QLabel(self.FRAME_inputType)
        self.LABEL_inputType.setGeometry(QtCore.QRect(10, 10, 171, 61))
        self.LABEL_inputType.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.LABEL_inputType.setObjectName("LABEL_inputType")
        self.PB_inputType1 = QtWidgets.QPushButton(self.FRAME_inputType)
        self.PB_inputType1.setGeometry(QtCore.QRect(170, 20, 150, 40))
        self.PB_inputType1.setObjectName("PB_inputType1")
        self.PB_inputType2 = QtWidgets.QPushButton(self.FRAME_inputType)
        self.PB_inputType2.setGeometry(QtCore.QRect(380, 20, 150, 40))
        self.PB_inputType2.setObjectName("PB_inputType2")

        #
        # FEEDBACK SCREEN
        self.FRAME_feedback = QtWidgets.QFrame(self.FRAME_main_window)
        self.FRAME_feedback.setGeometry(QtCore.QRect(150, 0, 601, 501))
        self.FRAME_feedback.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.FRAME_feedback.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.FRAME_feedback.setObjectName("FRAME_feedback")
        self.LABEL_feedback1 = QtWidgets.QLabel(self.FRAME_feedback)
        self.LABEL_feedback1.setGeometry(QtCore.QRect(10, 10, 171, 61))
        self.LABEL_feedback1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.LABEL_feedback1.setObjectName("LABEL_feedback1")
        self.LABEL_feedback2 = QtWidgets.QLabel(self.FRAME_feedback)
        self.LABEL_feedback2.setGeometry(QtCore.QRect(10, 10, 171, 61))
        self.LABEL_feedback2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.LABEL_feedback2.setObjectName("LABEL_feedback2")
        self.LABEL_feedback3 = QtWidgets.QLabel(self.FRAME_feedback)
        self.LABEL_feedback3.setGeometry(QtCore.QRect(10, 10, 171, 61))
        self.LABEL_feedback3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.LABEL_feedback3.setObjectName("LABEL_feedback3")
        self.PB_feedback = QtWidgets.QPushButton(self.FRAME_feedback)
        self.PB_feedback.setGeometry(QtCore.QRect(210, 370, 150, 40))
        self.PB_feedback.setObjectName("PB_feedback")

        #
        # SONG GALLERY SCREEN
        self.FRAME_songGallery = QtWidgets.QFrame(self.FRAME_main_window)
        self.FRAME_songGallery.setGeometry(QtCore.QRect(150, 0, 601, 501))
        self.FRAME_songGallery.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.FRAME_songGallery.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.FRAME_songGallery.setObjectName("FRAME_songGallery")
        self.LABEL_songGallery = QtWidgets.QLabel(self.FRAME_songGallery)
        self.LABEL_songGallery.setGeometry(QtCore.QRect(10, 10, 171, 61))
        self.LABEL_songGallery.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.LABEL_songGallery.setObjectName("LABEL_songGallery")
        self.LIST_songGallery = QtWidgets.QListWidget(self.FRAME_songGallery)
        self.LIST_songGallery.setGeometry(QtCore.QRect(20, 40, 256, 192))
        self.LIST_songGallery.setObjectName("LIST_songGallery")
        self.LABEL_songGallery_loading = QtWidgets.QLabel(self.FRAME_songGallery)
        self.LABEL_songGallery_loading.setGeometry(QtCore.QRect(10, 10, 171, 61))
        self.LABEL_songGallery_loading.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.LABEL_songGallery_loading.setObjectName("LABEL_songGallery_loading")
        self.LABEL_addSong_title = QtWidgets.QLabel(self.FRAME_songGallery)
        self.LABEL_addSong_title.setGeometry(QtCore.QRect(10, 10, 171, 61))
        self.LABEL_addSong_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.LABEL_addSong_title.setObjectName("LABEL_addSong_title")
        self.PB_addSong = QtWidgets.QPushButton(self.FRAME_songGallery)
        self.PB_addSong.setGeometry(QtCore.QRect(210, 40, 150, 40))
        self.PB_addSong.setObjectName("PB_addSong")
        self.PB_removeSong = QtWidgets.QPushButton(self.FRAME_songGallery)
        self.PB_removeSong.setGeometry(QtCore.QRect(210, 150, 150, 40))
        self.PB_removeSong.setObjectName("PB_removeSong")
        self.TB_addSong_title = QtWidgets.QPlainTextEdit(self.FRAME_songGallery)
        self.TB_addSong_title.setGeometry(QtCore.QRect(140, 380, 341, 31))
        self.TB_addSong_title.setObjectName("TB_addSong_title")
        self.PB_addSong_confirm = QtWidgets.QPushButton(self.FRAME_songGallery)
        self.PB_addSong_confirm.setGeometry(QtCore.QRect(210, 40, 150, 40))
        self.PB_addSong_confirm.setObjectName("PB_addSong_confirm")

        #
        # USER GUIDE SCREEN
        self.FRAME_userGuide = QtWidgets.QFrame(self.FRAME_main_window)
        self.FRAME_userGuide.setGeometry(QtCore.QRect(150, 0, 601, 501))
        self.FRAME_userGuide.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.FRAME_userGuide.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.FRAME_userGuide.setObjectName("FRAME_userGuide")
        self.LABEL_userGuide1 = QtWidgets.QLabel(self.FRAME_userGuide)
        self.LABEL_userGuide1.setGeometry(QtCore.QRect(10, 10, 171, 61))
        self.LABEL_userGuide1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.LABEL_userGuide1.setObjectName("LABEL_userGuide1")

        # user guide scroll area
        self.SCROLLAREA_userGuide = QtWidgets.QScrollArea(self.FRAME_userGuide)
        self.SCROLLAREA_userGuide.setGeometry(QtCore.QRect(0, 70, 601, 431))
        self.SCROLLAREA_userGuide.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.SCROLLAREA_userGuide.setWidgetResizable(True)
        self.SCROLLAREA_userGuide.setObjectName("SCROLLAREA_userGuide")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 599, 429))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.LABEL_userGuide2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.LABEL_userGuide2.setGeometry(QtCore.QRect(10, 10, 171, 61))
        self.LABEL_userGuide2.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeft)
        self.LABEL_userGuide2.setObjectName("LABEL_userGuide2")
        self.verticalLayout.addWidget(self.LABEL_userGuide2)
        self.SCROLLAREA_userGuide.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))

        # menu elements
        self.PB_play.setText(_translate("Dialog", "PLAY"))
        self.LABEL_logo.setText(_translate("Dialog", "TextLabel"))
        self.PB_user_guide.setText(_translate("Dialog", "USER GUIDE"))

        # mode selection elements
        self.LABEL_mode.setText(_translate("Dialog", "CHOOSE YOUR MODE"))
        self.PB_mode_1.setText(_translate("Dialog", "LEARNING"))
        self.PB_mode_2.setText(_translate("Dialog", "TESTING"))

        # song selection elements
        self.LABEL_song.setText(_translate("Dialog", "CHOOSE YOUR SONG"))
        
        # tempo selection elements
        self.SPIN_tempo.setSuffix(_translate("Dialog", "0"))
        self.PB_tempo_1.setText(_translate("Dialog", "PLAY WITHOUT TIMING"))
        self.PB_tempo_2.setText(_translate("Dialog", "PLAY WITH TIMING"))

        # final play button
        self.PB_play_2.setText(_translate("Dialog", "PLAY"))
        
        # in-progress label
        self.LABEL_inProgress.setText(_translate("Dialog", "SONG IN PROGRESS..."))

        # feedback elements
        self.LABEL_feedback1.setText(_translate("Dialog", "FEEDBACK"))
        self.LABEL_feedback2.setText(_translate("Dialog", "FEEDBACK"))
        self.LABEL_feedback3.setText(_translate("Dialog", "FEEDBACK"))
        self.PB_feedback.setText(_translate("Dialog", "RETURN TO PLAY SCREEN"))

        # input type elements
        self.LABEL_inputType.setText(_translate("Dialog", "CHOOSE INPUT TYPE"))
        self.PB_inputType1.setText(_translate("Dialog", "MIDI"))
        self.PB_inputType2.setText(_translate("Dialog", "MICROPHONE"))

        # song gallery elements
        self.LABEL_songGallery.setText(_translate("Dialog", "VIEW + EDIT YOUR SONG GALLERY"))
        self.PB_addSong.setText(_translate("Dialog", "ADD SONG"))
        self.PB_removeSong.setText(_translate("Dialog", "REMOVE SELECTED SONG"))
        self.LABEL_songGallery_loading.setText(_translate("Dialog", "YOUR SONG IS BEING ADDED ..."))
        self.LABEL_addSong_title.setText(_translate("Dialog", "WHAT IS THE NAME OF YOUR NEW SONG?"))
        self.PB_addSong_confirm.setText(_translate("Dialog", "CONFIRM"))

        # user guide labels
        self.LABEL_userGuide1.setText(_translate("Dialog", "HOW TO USE THE MOZARTMAKER"))
        self.LABEL_userGuide2.setText(_translate("Dialog", "INTRODUCTION\n\n1. Select the 'PLAY' tab on the left side of the screen.\n2. The menu tab will turn green to indicate your selection.\n3. In this view, select the mode that you would like to use followed by the song you would like to play.\n4. You can choose to play with or without tempo by selecting an option in the final row.\n5. If you choose to play with tempo, you can adjust your desired BPM by changing the number in the third row of options.\n6. When you have selected all of your desired settings, and you are ready to play, click the PLAY button at the bottom of the screen.\n\
                                                 \n\nMODE 1A: LEARNING MODE WITHOUT TIMING (Available with MIDI + Microphone)\n\nIf you are new to piano, this is the mode for you.\nIn this mode, you can learn which notes are played in the chosen song by progressing through them at your own pace.\nEach note to be played will be highlighted in green, once you play the correct note that's currently being projected.\nNo score will be displayed - it is simply for learning the basics of the song\n\
                                                 \n\nMODE 1B: LEARNING MODE WITH TIMING (Available with MIDI only)\n\nOnce you've perfected the notes for your song, you can move on to incorporate timing.\nIn this mode, the notes progress in the song at the pace of the chosen BPM, regardless of if you play the correct notes.\nWhen you press play, there will be an 8-beat count-in flashing on the first note to make you familiar with the tempo.\nAfter that, the correct notes and recommended finger placements will be highlighted on the keyboard.\nIf you play a note incorrectly, at the wrong time, or for the wrong duration, the next note will be projected in orange as a warning.\n\
                                                 \n\nMODE 2A: TESTING MODE WITHOUT TIMING (Available with MIDI + Microphone)\n\nIn this mode, the player must play the correct notes of the chosen song in the correct order regardless of the tempo.\nWhile playing, no feedback is provided to the players with the projector.\nWhen the correct number of notes have been detected (indicating the end of the song), an accuracy score will be displayed.\n\
                                                 \n\nMODE 2B: TESTING MODE WITH TIMING (Available with MIDI only)\n\nIn this mode, the user chooses a tempo and must play the correct notes at the chosen tempo.\nAt the start of the song, a count-in will commence, allowing the player to become familiar with the tempo and the first note.\nFor the rest of the song, the metronome will play, but there will be no feedback from the projector.\nAt the end of the song, 3 scores will be displayed:\n1. Note accuracy: based on the correctness of the notes played (regardless of timing)\n2. Timing accuracy: based on the correctness of when and for how long the notes were played (regardless of correctness)\n3. The overall score: averaging the correctness and timing scores.\n\
                                                 \n\nVIEW & EDIT SONG GALLERY\n\nWhen you select the 'SONG GALLERY' menu tab, you will see a list of songs in your gallery, with an option to ADD a new song or REMOVE one.\n1. ADD: To add a song, you will be prompted to enter a song title and select your sheet music file (.png, .jpg, .jpeg).\n2. REMOVE: To remove a song, simply select one from the list of songs, then click 'REMOVE SONG.'\n\
                                                 \n\nFINGER PLACEMENT\n\nIn learning mode, the projector will display a number between 1 and 5 on the keyboard.\nThese numbers indicate which right-hand finger you should play the note with.\n\
                                                 "))
